from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MasterOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_mode', models.CharField(choices=[('air', 'Air'), ('sea', 'Sea'), ('road', 'Road / Transit'), ('other', 'Other')], default='road', max_length=10)),
                ('operation_number', models.CharField(db_index=True, max_length=50)),
                ('customer_name', models.CharField(db_index=True, max_length=255)),
                ('operation_type', models.CharField(blank=True, choices=[('import', 'Import'), ('export', 'Export')], max_length=10)),
                ('declaration_number', models.CharField(blank=True, max_length=50)),
                ('bill_number', models.CharField(blank=True, max_length=100)),
                ('container_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('at_customs', 'At Customs'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('shipper_exporter', models.CharField(blank=True, max_length=255)),
                ('notify_party', models.CharField(blank=True, max_length=255)),
                ('ci_number', models.CharField(blank=True, max_length=100)),
                ('pl_number', models.CharField(blank=True, max_length=100)),
                ('shipping_line', models.CharField(blank=True, max_length=100)),
                ('vessel', models.CharField(blank=True, max_length=100)),
                ('port_of_loading', models.CharField(blank=True, max_length=100)),
                ('port_of_discharge', models.CharField(blank=True, max_length=100)),
                ('fcl_lcl', models.CharField(blank=True, max_length=10)),
                ('etd', models.CharField(blank=True, max_length=50)),
                ('eta', models.CharField(blank=True, max_length=50)),
                ('empty_container_return_date', models.CharField(blank=True, max_length=50)),
                ('awb_number', models.CharField(blank=True, max_length=50)),
                ('airline', models.CharField(blank=True, max_length=100)),
                ('flight_number', models.CharField(blank=True, max_length=50)),
                ('origin_airport', models.CharField(blank=True, max_length=100)),
                ('destination_airport', models.CharField(blank=True, max_length=100)),
                ('chargeable_weight', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=255)),
                ('driver_phone_ethiopia', models.CharField(blank=True, max_length=30)),
                ('driver_phone_djibouti', models.CharField(blank=True, max_length=30)),
                ('truck_plate_number', models.CharField(blank=True, max_length=50)),
                ('transport_association', models.CharField(blank=True, max_length=255)),
                ('association_phone', models.CharField(blank=True, max_length=30)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_phone', models.CharField(blank=True, max_length=30)),
                ('transport_rate', models.CharField(blank=True, max_length=50)),
                ('border_crossing', models.CharField(blank=True, max_length=100)),
                ('customs_branch', models.CharField(blank=True, max_length=100)),
                ('customs_model', models.CharField(blank=True, max_length=20)),
                ('gross_weight', models.CharField(blank=True, max_length=50)),
                ('net_weight', models.CharField(blank=True, max_length=50)),
                ('weight_incl_container', models.CharField(blank=True, max_length=50)),
                ('num_containers', models.CharField(blank=True, max_length=20)),
                ('num_items', models.CharField(blank=True, max_length=20)),
                ('num_packages', models.CharField(blank=True, max_length=20)),
                ('document_received_date', models.CharField(blank=True, max_length=50)),
                ('departure_date', models.CharField(blank=True, max_length=50)),
                ('do_collection_date', models.CharField(blank=True, max_length=50)),
                ('truck_assigned_date', models.CharField(blank=True, max_length=50)),
                ('gate_pass_date', models.CharField(blank=True, max_length=50)),
                ('loading_date', models.CharField(blank=True, max_length=50)),
                ('exit_date', models.CharField(blank=True, max_length=50)),
                ('customs_arrival_date', models.CharField(blank=True, max_length=50)),
                ('tax_payment_date', models.CharField(blank=True, max_length=50)),
                ('customs_release_date', models.CharField(blank=True, max_length=50)),
                ('factory_arrival_date', models.CharField(blank=True, max_length=50)),
                ('offloading_date', models.CharField(blank=True, max_length=50)),
                ('container_return_paper_date', models.CharField(blank=True, max_length=50)),
                ('empty_return_date', models.CharField(blank=True, max_length=50)),
                ('is_multimodal', models.BooleanField(default=False)),
                ('dry_port_name', models.CharField(blank=True, max_length=100)),
                ('dryport_arrival_date', models.CharField(blank=True, max_length=50)),
                ('dryport_departure_date', models.CharField(blank=True, max_length=50)),
                ('final_declaration_collected_date', models.CharField(blank=True, max_length=50)),
                ('container_bond_opening_date', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='masteroperation',
            index=models.Index(fields=['transport_mode', 'status'], name='master_data_transpo_9e5c1a_idx'),
        ),
    ]
