# Generated by Django 6.0.7 on 2026-08-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_database', '0002_transport_provider'),
        ('master_database', '0002_transport_structure'),
    ]

    operations = [
    ]
