# Generated by Django 6.0.7 on 2026-08-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_container_return_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='transport_mode',
            field=models.CharField(blank=True, choices=[('air', 'Air'), ('multimodal', 'Multimodal (Ocean + Djibouti Dry Port + inland leg)'), ('unimodal', 'Unimodal (Road only, Djibouti → Ethiopia)'), ('other', 'Other')], db_index=True, max_length=12),
        ),
        migrations.AddField(
            model_name='shipment',
            name='transport_provider',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
